numbers = input().split(", ")
positive_numbers = ", ".join([number for number in numbers if int(number) >= 0])
negative_numbers = ", ".join([number for number in numbers if int(number) < 0])
even_numbers = ", ".join([number for number in numbers if int(number) % 2 == 0])
odd_numbers = ", ".join([number for number in numbers if int(number) % 2 != 0])
print(f"Positive: {positive_numbers}")
print(f"Negative: {negative_numbers}")
print(f"Even: {even_numbers}")
print(f"Odd: {odd_numbers}")
